[project]
name = "mindset-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gtts>=2.5.4",
    "pygame>=2.6.1",
    "streamlit>=1.44.1",
]
